steps:
  - name: busybox
    args: ["false"] # Change to false to simulate failure

substitutions:
  # DEPLOYMENT INFO
  _APP_NAME: hono-getting-started
  _APP_SERVICE: api

  # GITHUB COMMIT INFO
  _COMMIT_USER: $(commit.commit.author.email)
  _COMMIT_URL: "https://github.com/khhini/hono-getting-started/commit/${COMMIT_SHA}"
  _COMMIT_MESSAGE: $(commit.commit.message)
  # ----

  # # CLOUD SOURCE REPO UPDATE EVENT INFO
  # _COMMIT_USER: $(csr.refUpdateEvent.email) 
  # _COMMIT_URL: https://source.cloud.google.com/ebc-source-code/ppn-trading-fe/+/${COMMIT_SHA}
  # # ----
options:
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true
